In [1]:
import numpy as np

In [2]:
## set random seed
np.random.seed(1234)

#### 1.随机数生成六个班的考试成绩，3门考试：Python、数学、语文。每个班50人

In [3]:
classes = []
for c in range(6):
    c = np.random.randint(101, size=(50, 3))
    classes.append(c)

In [4]:
class1 = classes[0]
class2 = classes[1]
class3 = classes[2]
class4 = classes[3]
class5 = classes[4]

In [5]:
class1

array([[ 47,  83,  38],
       [ 53,  76,  24],
       [ 15,  49,  23],
       [ 26,  30,  43],
       [ 30,  26,  58],
       [ 92,  69,  80],
       [ 73,  47,  50],
       [ 76,  37,  34],
       [ 38,  67,  11],
       [  0,  75,  80],
       [  3,   2,  19],
       [ 12,  65,  75],
       [ 81,  14,  71],
       [ 60,  46,  28],
       [ 81,  87,  13],
       [ 96,  12,  69],
       [ 95,  31,  89],
       [ 84,  45,  16],
       [ 41,  72,  56],
       [ 70,  56,  86],
       [ 44,  90,  83],
       [ 47,  49,  18],
       [ 85,  46,  98],
       [ 37,  38,   7],
       [100,  67,   5],
       [ 47,  47,  15],
       [ 34,  10,  28],
       [  4,  82,  89],
       [ 55,  78,  23],
       [ 50,  62,  55],
       [ 84,   0,  98],
       [ 90,  33,  21],
       [ 71,  68,  81],
       [ 52,  64,  85],
       [ 41,   1,  14],
       [  3,  30,  12],
       [ 73,  19,  26],
       [ 96,  68, 100],
       [ 64,  22,  56],
       [ 84,   8,  44],
       [ 24,  94,  15],
       [ 72,   2

#### 2.将六个班的考试成绩进行合并得到score

In [6]:
score = np.concatenate(tuple(classes), axis=0)
score.shape

(300, 3)

In [7]:
score

array([[ 47,  83,  38],
       [ 53,  76,  24],
       [ 15,  49,  23],
       [ 26,  30,  43],
       [ 30,  26,  58],
       [ 92,  69,  80],
       [ 73,  47,  50],
       [ 76,  37,  34],
       [ 38,  67,  11],
       [  0,  75,  80],
       [  3,   2,  19],
       [ 12,  65,  75],
       [ 81,  14,  71],
       [ 60,  46,  28],
       [ 81,  87,  13],
       [ 96,  12,  69],
       [ 95,  31,  89],
       [ 84,  45,  16],
       [ 41,  72,  56],
       [ 70,  56,  86],
       [ 44,  90,  83],
       [ 47,  49,  18],
       [ 85,  46,  98],
       [ 37,  38,   7],
       [100,  67,   5],
       [ 47,  47,  15],
       [ 34,  10,  28],
       [  4,  82,  89],
       [ 55,  78,  23],
       [ 50,  62,  55],
       [ 84,   0,  98],
       [ 90,  33,  21],
       [ 71,  68,  81],
       [ 52,  64,  85],
       [ 41,   1,  14],
       [  3,  30,  12],
       [ 73,  19,  26],
       [ 96,  68, 100],
       [ 64,  22,  56],
       [ 84,   8,  44],
       [ 24,  94,  15],
       [ 72,   2

#### 3.生成性别数组sex，水平叠加数组sex和score得到data

In [8]:
sex = np.random.randint(2, size=(score.shape[0], 1))
sex

array([[1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [9]:
data = np.hstack((score, sex))
data.shape

(300, 4)

In [10]:
data

array([[47, 83, 38,  1],
       [53, 76, 24,  0],
       [15, 49, 23,  1],
       ...,
       [72, 48, 56,  1],
       [44, 79, 86,  0],
       [86,  1, 51,  1]])

#### 4.分别计算男女生各科成绩统计指标：最小值、最大值、平均分、中位数、标准差

In [11]:
def course_stats(data, course_idx):
    if course_idx == 0:
        course = 'Python'
    elif course_idx == 1:
        course = '数学'
    else:
        course = '语文'
        
    min_ = np.min(data)
    max_ = np.max(data)
    mean_ = np.mean(data)
    median_ = np.median(data)
    std_ = np.std(data)
    
    print(f'{course}科目成绩：最小值为{min_}，最大值为{max_}，平均分为{mean_}，中位数为{median_}，标准差为{std_}')
    return
    

In [12]:
def stats(data, sex):
    if sex == 1:
        sex_ = '女生'
    if sex == 0:
        sex_ = '男生'
    print(f'【{sex_}成绩统计】')
    
    subset = data[data[:,3]==sex]
        
    for c in range(subset.shape[1]-1):
        course_stats(subset[:,c], c)
    print()
    return


In [13]:
stats(data, 0)
stats(data, 1)

【男生成绩统计】
Python科目成绩：最小值为0，最大值为100，平均分为49.4496644295302，中位数为51.0，标准差为28.41670655260367
数学科目成绩：最小值为0，最大值为100，平均分为49.91275167785235，中位数为51.0，标准差为29.204654608769655
语文科目成绩：最小值为1，最大值为99，平均分为51.060402684563755，中位数为50.0，标准差为26.872612286731876

【女生成绩统计】
Python科目成绩：最小值为0，最大值为97，平均分为50.47682119205298，中位数为53.0，标准差为29.113351079654727
数学科目成绩：最小值为0，最大值为100，平均分为48.47019867549669，中位数为48.0，标准差为28.11890739236965
语文科目成绩：最小值为0，最大值为100，平均分为53.788079470198674，中位数为53.0，标准差为28.44946938401655

